<div class="row">

    {{--<div class="row">--}}
        {{--<div class="col-md-8 col-md-offset-2 text-center">--}}
            {{--<h1>Iont Detector</h1>--}}
        {{--</div>--}}
    {{--</div>--}}

    {{--<div class="row">--}}
        {{--<div class="col-md-8 col-md-offset-2 text-center">--}}
            {{--<h3>Public RSA key vulnerability checker</h3>--}}
        {{--</div>--}}
    {{--</div>--}}

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">

                        <div class="col-md-8 col-md-offset-2 text-center">
                            <h1>Iont Detector</h1>
                        </div>
                        <div class="col-md-8 col-md-offset-2 text-center">
                            <h3>Public RSA key vulnerability checker</h3>
                        </div>

                        <div class="col-md-12">
                            <p>
                                This tools is aimed to help you detect whether you are vulnerable to recently discovered
                                attack on RSA keys
                                generated by particular sources. For more information see our <a
                                        href="https://keychest.net">blog</a>.
                            </p>

                            <p>
                                <strong>Privacy notice:</strong> We do not collect any user data. The keys are not
                                stored. After analysis
                                are done they are forgotten.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <tester></tester>

</div>
