<?php

namespace App\Events;

use App\Keychest\Queue\JsonJob;

use Illuminate\Queue\SerializesModels;


use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;


/**
 * Class ScanJobProgress
 * Event generated by the Keychest Scanner.
 * It is explicitly consumed by App\Listeners\ScanJobListener.
 *
 * @package App\Events
 */
class ScanJobProgress implements JsonJob
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * json encoded data passed by python scanner
     * @var string
     */
    protected $json_data;

    /**
     * Create a new event instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Returns json interpretation
     * @return array
     */
    public function toJson()
    {
        return [];
    }

    /**
     * @return string
     */
    public function getJsonData()
    {
        return $this->json_data;
    }


}
