<?php

namespace App\Events;

use App\Keychest\Queue\JsonJob;

use Illuminate\Queue\SerializesModels;


use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Support\Facades\Log;


/**
 * Class TesterJobProgress
 * Event generated by the Keychest Scanner (tester part).
 * It is explicitly consumed by App\Listeners\TesterJobListener.
 *
 * @package App\Events
 */
class TesterJobProgress implements JsonJob
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * json encoded data passed by python scanner
     * @var string
     */
    protected $json_data;

    /**
     * Cached version of data - after decoding from json
     * @var
     */
    protected $data;

    /**
     * Create a new event instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Returns json interpretation
     * @return array
     */
    public function toJson()
    {
        return [];
    }

    /**
     * @return string
     */
    public function getJsonData()
    {
        return $this->json_data;
    }

    /**
     * Attempts to decode json data
     * @return mixed|null
     */
    public function getData()
    {
        if ($this->data !== null){
            return $this->data;
        }

        try{
            $this->data = json_decode($this->getJsonData());
        } catch(\Exception $e){
            Log::error('Exception in event data decode: ' . $e);
        }

        return $this->data;
    }


}
