<?php
/**
 * Created by PhpStorm.
 * User: dusanklinec
 * Date: 26.05.17
 * Time: 14:31
 */

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

/**
 * Access tokens
 *
 * Class AccessToken
 * @package App\Models
 */
class AccessToken extends Model
{
    const TABLE = 'access_tokens';

    protected $guarded = array();

    protected $table = self::TABLE;

    /**
     * Token to send - generated by token repository
     * @var
     */
    protected $tokenToSend;

    public function getDates()
    {
        return ['created_at', 'expires_at', 'sent_at', 'last_sent_at'];
    }

    /**
     * Associated user
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(){
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    /**
     * Associated user
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function apiKey(){
        return $this->belongsTo('App\Models\ApiKey', 'api_key_id');
    }

    /**
     * @return mixed
     */
    public function getTokenToSend()
    {
        return $this->tokenToSend;
    }

    /**
     * @param mixed $tokenToSend
     */
    public function setTokenToSend($tokenToSend)
    {
        $this->tokenToSend = $tokenToSend;
    }
}
